[tools]
java = "temurin-21.0.2+13.0.LTS"
clojure = "1.12.1.1550"
babashka = "1.12.206"
clj-kondo = "2025.06.05"
cljfmt = "0.13.1"
tailwindcss = "4.1.11"

[alias]
cljfmt = "asdf:https://github.com/b-social/asdf-cljfmt"
tailwindcss = "asdf:https://github.com/virtualstaticvoid/asdf-tailwindcss"
